In [2]:
import numpy as np

In [2]:
a1=np.array([1,2,3])
print(a1)

[1 2 3]


In [3]:
type(a1)

numpy.ndarray

In [4]:
a2=np.array([[1,2,3.3],
            [4,5,6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
import numpy as np

# Create a 3x3x3 array (3 layers of 3x3 matrices)
array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                     [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                     [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

print(array_3d)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [6]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [8]:
array_3d.shape

(3, 3, 3)

In [9]:
a2.shape

(2, 3)

In [10]:
a1.ndim

1

In [12]:
a2.ndim

2

In [14]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

a3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [15]:
a2.ndim,a3.ndim

(2, 3)

In [16]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [17]:
a1.size,a2.size,a3.size

(3, 6, 27)

In [18]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [20]:
import pandas as pd
df2=pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [22]:
sample_array= np.array([1,2,3])
sample_array.dtype

dtype('int64')

In [26]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
zeros=np.zeros((2,3))

In [28]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [31]:
# Generate a 3x5 array with random values between 0 and 10
random_array = np.random.randint(0, 10, size=(3, 5))
random_array


array([[8, 6, 7, 4, 7],
       [0, 0, 2, 6, 9],
       [2, 7, 1, 2, 4]])

In [33]:
# Generate a 3x5 array with random values between 0 and 10
random_array1 = np.random.uniform(0, 10, size=(3, 5))
random_array1


array([[6.98542306, 5.75262572, 9.32037134, 7.41053137, 3.73247486],
       [9.11433928, 8.76410829, 3.26618754, 1.18090187, 8.29281965],
       [7.06864985, 6.14802519, 2.53629336, 9.63961744, 4.13543614]])

In [34]:
random_array.shape

(3, 5)

In [39]:
# pseudo numbers
np.random.seed(seed=0)
random_array2 = np.random.randint(0, 10, size=(3, 5))
random_array2

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [40]:
np.unique(random_array2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1

array([1, 2, 3])

In [42]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [47]:
a3[:3,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]],

       [[19, 20],
        [22, 23]]])

In [48]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [53]:
a4.ndim

4

In [54]:
# Create two arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Addition
add_result = a + b  # [6, 8, 10, 12]

# Subtraction
sub_result = a - b  # [-4, -4, -4, -4]

# Multiplication
mul_result = a * b  # [5, 12, 21, 32]

# Division
div_result = a / b  # [0.2, 0.333..., 0.428..., 0.5]

print(add_result, sub_result, mul_result, div_result)


[ 6  8 10 12] [-4 -4 -4 -4] [ 5 12 21 32] [0.2        0.33333333 0.42857143 0.5       ]


In [55]:
# Create an array
a = np.array([10, 20, 30])

# Addition
add_scalar = a + 5  # [15, 25, 35]

# Subtraction
sub_scalar = a - 5  # [5, 15, 25]

# Multiplication
mul_scalar = a * 2  # [20, 40, 60]

# Division
div_scalar = a / 2  # [5, 10, 15]

print(add_scalar, sub_scalar, mul_scalar, div_scalar)


[15 25 35] [ 5 15 25] [20 40 60] [ 5. 10. 15.]


In [56]:
# Create a 2D array and a 1D array
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([1, 2, 3])

# Broadcasting B across A
broadcast_result = A + B

print(broadcast_result)


[[2 4 6]
 [5 7 9]]


In [57]:
# Square root
sqrt_result = np.sqrt(np.array([4, 9, 16]))  # [2.0, 3.0, 4.0]

# Exponentiation
exp_result = np.power(np.array([2, 3, 4]), 2)  # [4, 9, 16]

print(sqrt_result, exp_result)


[2. 3. 4.] [ 4  9 16]


In [58]:
# Create an array
a = np.array([1, 2, 3, 4])

# Sum of all elements
sum_result = np.sum(a)  # 10

# Mean of all elements
mean_result = np.mean(a)  # 2.5

# Minimum and maximum
min_result = np.min(a)  # 1
max_result = np.max(a)  # 4

print(sum_result, mean_result, min_result, max_result)


10 2.5 1 4


In [3]:
high_var_array=np.array([1,100,200,500,4000,500000])
low_var_array=np.array([1,4,5,8,14,18])
print(np.var(high_var_array))
print(np.var(low_var_array))

34590937511.25
34.88888888888889


In [4]:
np.std(high_var_array),np.std(low_var_array)

(185986.39066138683, 5.90668171555645)